DROP TABLE IF EXISTS images;
CREATE TABLE images (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  prompt VARCHAR(155) NOT NULL,
  path VARCHAR(155) NOT NULL,
  user_id VARCHAR(155) NOT NULL,
  public BOOL DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
